name: Deploy to AWS Lightsail using PEM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Lightsail PEM SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.LIGHTSAIL_PEM_KEY }}" > ~/.ssh/lightsail.pem
        chmod 600 ~/.ssh/lightsail.pem
        ssh-keyscan -p ${{ secrets.LIGHTSAIL_PORT }} -H ${{ secrets.LIGHTSAIL_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Lightsail via SSH
      run: |
        ssh -i ~/.ssh/lightsail.pem -p ${{ secrets.LIGHTSAIL_PORT }} ${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
          cd /home/ubuntu/Full-Fill
          git pull origin main
          npm install
          pm2 restart app
        EOF